
local curent_wave = 1
local enemy_duy = 0
local enemy_win = 0

local waves = {}
waves[1] = {"ghost", 16}

local function spawn_enemy(self, timer_handle)
	if (self.count >= waves[curent_wave][2]) then
		timer.cancel(timer_handle)
	end
	self.count = self.count + 2
	msg.post("/spawner1#ghost_spawner", waves[curent_wave][1], {ad=-1})
	msg.post("/spawner2#ghost_spawner", waves[curent_wave][1]) 
		
end

function init(self)
	self.count = 0
	timer.delay(1, true, spawn_enemy)
end